### ISSUE TITLE
dependency error

### ISSUE THREAD

**Issue by acer9997** [jstray/cjworkbench#1]
Trying to look at this on my home server but running into some dependency issues. Following your guide, I get these errors:

```
WebpackError at /workflows/
            ModuleNotFoundError in 
            Module not found: Error: Can't resolve 'chartbuilder-ui/dist/styles.css' in '/Users/acer9997/Projects/cjworkbench/cjworkbench/assets/js'
```

**Comment by jstray** [comment]
Hmm, do you have a cjworkbench/chartbuilder/chartbuilder-ui folder? There may have been some problem with the git submodule.

**Comment by acer9997** [comment]
I do not, the directories are there but they're empty.

**Comment by jstray** [comment]
Hmm. Try doing git submodule update --recursive from the command line?

**Comment by acer9997** [comment]
Thanks @jstray 
Pulled submodules with:
`git pull && git submodule init && git submodule update && git submodule status`

**Comment by jstray** [comment]
So it's working now?

**Comment by acer9997** [comment]
Unfortunately not yet, getting the following error now:

```
➜  cjworkbench git:(master) ./node_modules/.bin/webpack --config webpack.config.js --watch
module.js:472
    throw err;
    ^

Error: Cannot find module '../package.json'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/acer9997/Projects/cjworkbench/cjworkbench/node_modules/.bin/webpack:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by jstray** [comment]
Hmm. Could be an outdated version of node. What does node --version give you?

**Comment by acer9997** [comment]
V7.7.1

**Comment by jstray** [comment]
Should be ok. I presume you did an npm install? Any other ideas?

**Comment by acer9997** [comment]
Oddly, I had this part running the other day, and I recently ran a brew upgrade between then and now… this upgraded me to Python 3.6, then had to troubleshoot some issues openssl and also the Python cryptography package… I don’t know if Node uses any Python components or otherwise has any dependencies on packages that Brew installs.

**Comment by jstray** [comment]
I don't think node has python dependencies... I think there may also be a couple missing packages in package.json... but I don't know what is causing this particular error

**Comment by acer9997** [comment]
Got it working - removed node_modules and reinstalled. Must have been something caused by my recent brew update.

Thanks!
